pipeline {
    agent any

    environment {
        // --- CONFIGURE THESE ---
        GITHUB_REPO        = 'https://github.com/hassanjee/nginx-web-repo.git'  // GitHub repo URL
        GITHUB_BRANCH      = 'main'
        DOCKERHUB_USERNAME = 'hjavedengineer'
        IMAGE_NAME         = 'nginx-web-server'
        // -----------------------

        IMAGE_TAG          = "${DOCKERHUB_USERNAME}/${IMAGE_NAME}:${BUILD_NUMBER}"
        IMAGE_LATEST       = "${DOCKERHUB_USERNAME}/${IMAGE_NAME}:latest"
        DOCKERHUB_CREDS    = credentials('dockerhub-credentials')   // Jenkins credential ID
        // GITHUB_CREDS       = credentials('github-credentials')       // Jenkins credential ID (if private repo)
    }

    triggers {
        // Poll GitHub every minute for changes
        // Replace with GitHub webhook for instant triggering (recommended)
        pollSCM('* * * * *')
    }

    options {
        buildDiscarder(logRotator(numToKeepStr: '10'))
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()
    }

    stages {

        // ─────────────────────────────────────────────
        // STAGE 1 — Pull latest code from GitHub
        // ─────────────────────────────────────────────
        stage('Checkout') {
            steps {
                echo "📥 Pulling latest code from GitHub..."
                git(
                    url: "${GITHUB_REPO}",
                    branch: "${GITHUB_BRANCH}",
                    credentialsId: 'github-credentials'   // remove if public repo
                )
                echo "✅ Code pulled. Commit: ${env.GIT_COMMIT}"
            }
        }

        // ─────────────────────────────────────────────
        // STAGE 2 — Install dependencies & run tests
        // ─────────────────────────────────────────────
        stage('Install & Test') {
            steps {
                echo "📦 Installing Node dependencies..."
                sh 'apt-get update && apt-get install -y nodejs npm'  // Ensure Node.js is installed
                sh 'npm install'

                echo "🧪 Running tests..."
                sh 'npm test --if-present'
            }
        }

        // ─────────────────────────────────────────────
        // STAGE 3 — Build Dockerfile (generate if missing)
        // ─────────────────────────────────────────────
        stage('Prepare Dockerfile') {
            steps {
                echo "🐳 Checking for Dockerfile..."
                sh '''
                    if [ ! -f Dockerfile ]; then
                        echo "No Dockerfile found — generating one for Node.js app..."

                        # Detect Node version from .nvmrc or package.json, fallback to 20
                        if [ -f .nvmrc ]; then
                            NODE_VER=$(cat .nvmrc | tr -d "v")
                        elif command -v node >/dev/null 2>&1; then
                            NODE_VER=$(node -e "const p=require('./package.json'); console.log((p.engines&&p.engines.node||'20').replace(/[^0-9.]/g,'').split('.')[0])")
                        else
                            NODE_VER=20
                        fi

                        # Detect start script
                        START_CMD=$(node -e "const p=require('./package.json'); console.log(p.scripts&&p.scripts.start ? 'npm start' : 'node index.js')" 2>/dev/null || echo "npm start")

                        cat > Dockerfile <<EOF
# Auto-generated by Jenkins pipeline
FROM node:${NODE_VER}-alpine AS deps
WORKDIR /app
COPY package*.json ./
RUN npm ci --only=production

FROM node:${NODE_VER}-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY --from=deps /app/node_modules ./node_modules
COPY . .
EXPOSE 3000
CMD ["${START_CMD}"]
EOF
                        echo "✅ Dockerfile generated."
                    else
                        echo "✅ Dockerfile already exists."
                    fi
                    cat Dockerfile
                '''
            }
        }

        // ─────────────────────────────────────────────
        // STAGE 4 — Build Docker image
        // ─────────────────────────────────────────────
        stage('Build Docker Image') {
            steps {
                echo "🔨 Building Docker image: ${IMAGE_TAG}"
                sh "docker build -t ${IMAGE_TAG} -t ${IMAGE_LATEST} ."
                echo "✅ Image built successfully."
            }
        }

        // ─────────────────────────────────────────────
        // STAGE 5 — Push image to DockerHub
        // ─────────────────────────────────────────────
        stage('Push to DockerHub') {
            steps {
                echo "🚀 Pushing image to DockerHub..."
                sh '''
                    echo "$DOCKERHUB_CREDS_PSW" | docker login -u "$DOCKERHUB_CREDS_USR" --password-stdin
                    docker push ''' + IMAGE_TAG + '''
                    docker push ''' + IMAGE_LATEST + '''
                    docker logout
                '''
                echo "✅ Image pushed: ${IMAGE_TAG}"
            }
        }

        // ─────────────────────────────────────────────
        // STAGE 6 — Deploy with Docker Compose
        // ─────────────────────────────────────────────
        stage('Deploy with Docker Compose') {
            steps {
                echo "⚙️  Deploying app with Docker Compose..."
                sh '''
                    # Pull the freshly pushed image
                    docker compose pull

                    # Recreate only changed containers, keep others running
                    docker compose up -d --remove-orphans

                    # Show running containers
                    docker compose ps
                '''
                echo "✅ App is running!"
            }
        }

        // ─────────────────────────────────────────────
        // STAGE 7 — Health check
        // ─────────────────────────────────────────────
        stage('Health Check') {
            steps {
                echo "🏥 Running health check..."
                sh '''
                    sleep 5
                    # Adjust port/endpoint if needed
                    curl -sf http://localhost:3000/health || \
                    curl -sf http://localhost:3000 || \
                    echo "⚠️  Health check endpoint not reachable — verify manually."
                '''
            }
        }
    }

    // ─────────────────────────────────────────────
    // POST actions
    // ─────────────────────────────────────────────
    post {
        success {
            echo "🎉 Pipeline succeeded! Image ${IMAGE_TAG} is live."
            // Add Slack/email notification here if needed
        }
        failure {
            echo "❌ Pipeline failed. Check the logs above."
            // Roll back: docker compose down && docker compose up -d --scale app=0
        }
        always {
            // Clean up dangling images to save disk space
            sh 'docker image prune -f || true'
        }
    }
}
